package com.reactive.programming;

import com.reactive.programming.helper.DefaultSubscriber;
import com.reactive.programming.helper.Util;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import reactor.core.publisher.Flux;

/**
 *  - Flux.create() produces a Cold Publisher by default (where each subscriber will have its own FluxSink).
 *  - A FluxSink is tied to a single subscriber.
 *  - When we call Flux.create(), Reactor gives you a callback that runs per subscription. Inside that callback, we get a fresh FinkSink for
 *      every new subscription.
 *  - We can't share one fluxSink across multiple subscribers.
 *  - If we try to hold onto a fluxSink & push data into it after multiple subscribers have come in, only the subscriber associated with
 *      that fluxSink will see those signal. The others won't
 *          - Flux.create(callback)
 *              -> Subscriber A -> callback invoked -> FluxSink A
 *              -> Subscriber B -> callback invoked -> FluxSink B
 *              -> Subscriber C -> callback invoked -> FluxSink C
 *              -> ...
 *          - Each subscriber triggers the callback again, producing a new sink. That's why we can't have "multiple subscribers for the same FluxSink".

 *  - In below example, we've created just one instance of NameGenerator, shared it across multiple threads/fluxSinks & this instance
 *      will accept 2 different FluxSink for 2 different subscribers & the later subscriber will reinitialize the sink (initialized by 1st subscriber)
 *
 *  - Hence, we will not see the data generated by 1st subscriber as the generator.generate() will use this NameGenerator's sink object to call next() method.
 *
 */
public class FluxSinkIssue {

    private static final Logger log = LoggerFactory.getLogger(FluxSinkIssue.class);
    public static void main(String[] args) {

        // NameGenerator is a consumer of FluxSink
        NameGenerator generator = new NameGenerator();
        log.info("NameGenerator instance created: [{}]", generator.hashCode());

        // For each new subscriber, a new FluxSink  will be created.
        var flux = Flux.create(generator);
        log.info("Flux created: {}", flux);

        flux.subscribe(DefaultSubscriber.create("sub1"));

        // This will get new fluxSink instance & in accept() method, the sink will be reinitialized.
        flux.subscribe(DefaultSubscriber.create("sub2"));

        for (int i = 0; i < 10; i++) {
            // generator.generate() will use this NameGenerator's sink object to call next() method.
            generator.generate();
        }
    }
}
